---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  ports:
    - port: 80
      name: http-ncloud
      protocol: TCP
      targetPort: http-ncloud
    - port: 8080
      name: http-nc
      protocol: TCP
      targetPort: http-nc
    - port: 8443
      name: https-nc
      protocol: TCP
      targetPort: https-nc
  selector:
    app: nextcloud
